# Generated by Django 5.0 on 2024-05-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api_app', '0002_alter_customuser_age_alter_customuser_cnic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phno',
            field=models.BigIntegerField(default=False),
        ),
    ]
