# Generated by Django 5.0 on 2024-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api_app', '0003_alter_customuser_phno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cnic',
            field=models.BigIntegerField(default=False),
        ),
    ]
